### ISSUE TITLE
Using EarthEngineTerrainLayer with to_html()

### ISSUE THREAD

**Issue by giswqs** [UnfoldedInc/earthengine-layers#101]
I tested the `to_html()` method with the `EarthEngineTerrainLayer`. It seems only the terrain layer is saved to the html, while the image layer is missing. 

![](https://i.imgur.com/ax5TqfQ.png)

**Comment by kylebarron** [comment]
I never got `to_html` to work with either Earth Engine layer. But more broadly, `to_html()` isn't very useful here because the Google EE API token is only valid for 1 hour, so you'd need to manually run `to_html()` again every hour.

This should probably be added to the docs

**Comment by giswqs** [comment]
@kylebarron Thanks for the info! Google EE API token is not an issue, as the notebook can be deployed using [Voila](https://voila.readthedocs.io/en/stable/) and the html can be generated on-the-fly, similar to my [Landsat timelapse app](https://geemap.herokuapp.com/voila/render/timelapse.ipynb). Since the `to_html` does not work with pydeck ee layers, I am closing this issue. Thanks.

**Comment by kylebarron** [comment]
> as the notebook can be deployed using [Voila](https://voila.readthedocs.io/en/stable/) and the html can be generated on-the-fly,

For the HTML to be generated on the fly, your Google credentials would need to be saved either within the JS or the instance running Jupyter. This is discouraged and could possibly give an attacker access (to portions of) your Google account.

**Comment by giswqs** [comment]
The EE token can be set as an environment variable on the cloud server, just like the GitHub secrets. As long as the cloud server is secure, it should be fine. Of course, running on public instances such as Binder is not recommended. 

![](https://i.imgur.com/WDp8z7h.png)
