### ISSUE TITLE
Compatibility with streamlit

### ISSUE THREAD

**Issue by giswqs** [UnfoldedInc/earthengine-layers#120]
I am trying to use earthengine-layers with [streamlit](https://streamlit.io/) for developing interactive web apps. The following code works fine in Jupyter notebook. When using the same code with streamlit, I got the error `JSON converter: No registered class of type`. Earth Engine layers do not show up on the map. Any advice?

```python
from pydeck_earthengine_layers import EarthEngineLayer
import pydeck as pdk
import ee

# Initialize Earth Engine library
try:
    ee.Initialize()
except Exception as e:
    ee.Authenticate()
    ee.Initialize()

# Create an Earth Engine object
image = ee.Image('CGIAR/SRTM90_V4')

# Define Earth Engine visualization parameters
vis_params = {
    "min": 0, 
    "max": 4000,
    'palette': ['006633', 'E5FFCC', '662A00', 'D8D8D8', 'F5F5F5']
}

# Create a pydeck EarthEngineLayer object, using the Earth Engine object and
# desired visualization parameters
ee_layer = EarthEngineLayer(image, vis_params)

# Define the initial viewport for the map
view_state = pdk.ViewState(latitude=37.7749295, longitude=-122.4194155, zoom=10, bearing=0, pitch=45)

# Create a Deck instance, and display in Jupyter
r = pdk.Deck(layers=[ee_layer], initial_view_state=view_state)
r
```
![image](https://user-images.githubusercontent.com/5016453/137220221-aaff8a84-0577-42fc-9bee-9e48998f5355.png)

**Comment by ibgreen** [comment]
The pydeck_earthengine_layers module is special in that it depends on the pydeck JavaScript widget dynamically loading an external JavaScript script that injects the earthengine deck.gl layers. 

(this is different since all other pydeck layers are bundled inside pydeck)

Haven't looked at how streamlit is integrating pydeck but suspect that either the dynamic loading part of javascript layer modules is not included, or streamlit has some issue is preventing the dynamic load from completing.

This dynamic loading bit is relatively tricky to debug and may require someone to some deep digging.

**Comment by giswqs** [comment]
@ibgreen Thanks for the insights. Here are two links to the pydeck implementation in streamlit. 

- https://docs.streamlit.io/library/api-reference/charts/st.pydeck_chart
- https://github.com/streamlit/streamlit/blob/develop/lib/streamlit/elements/deck_gl_json_chart.py#L23

**Comment by giswqs** [comment]
Here is a streamlit app I developed using geemap and streamlit. I would love to use pydeck and earthengine-layers. 
https://share.streamlit.io/giswqs/geemap-apps/app.py

**Comment by kylebarron** [comment]
This is the same as https://github.com/visgl/deck.gl/issues/6278 I believe. I'm guessing streamlit is only including core modules

**Comment by giswqs** [comment]
@kylebarron Thank you for pointing to the deck.gl issue. Does this mean that the issue has to be fixed by streamlit? Or is it something can be fixed by pydeck or earthengine-layers?
I tried `st.pydeck_chart(r.to_html())`, the basemap shows up, but not GEE layers.
