### ISSUE TITLE
Map rendering error - authentication issue

### ISSUE THREAD

**Issue by giswqs** [UnfoldedInc/earthengine-layers#123]
It seems earthengine-layers no longer works. The map fails to render. See the error below when running the terrain example. 

Relevant issue: https://github.com/giswqs/geemap/issues/907

https://github.com/UnfoldedInc/earthengine-layers/blob/master/py/examples/terrain.ipynb

![image](https://user-images.githubusercontent.com/5016453/152665126-e709cdf0-c9f8-4228-a3fa-db1c39d0dd29.png)

**Comment by rsignell-usgs** [comment]
@kylebarron any ideas?

**Comment by kylebarron** [comment]
Hey @giswqs, thanks for the bug report. 

I'm able to reproduce that console error. It looks like the JavaScript EE API has changed the allowed authentication methods, and they may have removed token support? The Python bindings were designed to create their own token, which prevented the long-lived refresh token from needing to be passed from Python to JS.
https://github.com/UnfoldedInc/earthengine-layers/blob/9d3ee980660ebcc6719c881922974e699920669c/py/pydeck_earthengine_layers/pydeck_earthengine_layers.py#L109-L116

You can see this token when you log the `repr` of a layer
<img width="648" alt="image" src="https://user-images.githubusercontent.com/15164633/154317483-bebf009f-c00c-45bf-bbaf-b9d58611b176.png">
This token is then set using `ee.apiclient.setAuthToken`.
https://github.com/UnfoldedInc/earthengine-layers/blob/9d3ee980660ebcc6719c881922974e699920669c/modules/earthengine-layers/src/ee-api.js#L29-L34

The [API Changelog](https://developers.google.com/earth-engine/changelog) is pretty verbose. Do you happen to know if the EE team removed token support? If so, we'd need to rethink how Pydeck's authentication works.

**Comment by ibgreen** [comment]
@dag-ee

**Comment by giswqs** [comment]
@kylebarron I remembered that the EE team made some changes to the authentication method in November 2021, which caused some issues. See this [thread](https://groups.google.com/g/google-earth-engine-developers/c/jhMWdmdFoVY/m/Hd5WhMCrBAAJ) in the GEE Developer Forum. I thought they already reverted the changes. I have been using the Python API. It is working fine. 

@tylere @jdbcode might be able to provide some advice on this.

**Comment by kylebarron** [comment]
> I have been using the Python API. It is working fine.

Note that here we're using the EE JS API for authentication, not the EE Python API. (The EE Python API is only used to create representations of `ee.Image` objects that can be serialized and sent to the JS side for actual rendering). The Python code here does a normal `requests.post` against the Google OAuth2 endpoint to get a short-lived OAuth access token. Then passes that access token to the JS side.

**Comment by dag-ee** [comment]
Hi!  What environment are you using to reproduce this - can you share a link to a system which shows the error?  The setAuthToken call should still behave the same way, and ee.apiclient.authToken_ should get set to 'Bearer xxx'.

Also, make sure you check  the box for "View and manage your Google Earth Engine data." on the initialization consent screen.  If you've already gone through this, you may have to go to https://myaccount.google.com/permissions and remove the authenticator app first.

To check if a token has the valid EE permissions: https://www.googleapis.com/oauth2/v3/tokeninfo?access_token=xxx

That November thread is an unrelated issue.
