### ISSUE TITLE
Example with Google Maps basemap

### ISSUE THREAD

**Issue by kylebarron** [UnfoldedInc/earthengine-layers#38]
It would be nice to create an example using the Google Maps overlay. It's most likely that such an example would have to be done as a Pure JS example, as the Google Maps JS package doesn't officially support React.

JS:

- [x] Working `GoogleMapsOverlay` example without EarthEngine. The [docs](https://deck.gl/#/documentation/submodule-api-reference/deckgl-google-maps/google-maps-overlay) don't seem to have a full reproducible example.
- [x] EarthEngine example with Google Maps basemap
- [ ] Prevent tilting by passing custom `controller`

Pydeck: 

- [x] Support Google Maps basemap option in `pydeck` (should be fixed in pydeck now)
- [ ] Prevent tilting

**Comment by giswqs** [comment]
Here is my basemap example with geemap. Not sure if it would work with pydeck. 

- [Using basemaps in geemap and ipyleaflet for interactive mapping with Google Earth Engine](#2-using-basemaps-in-geemap-and-ipyleaflet-for-interactive-mapping-with-google-earth-engine) ([video](https://youtu.be/6J5ZCIUPXfI) | [gif](https://i.imgur.com/P5B2f7p.gif) | [notebook](https://github.com/giswqs/geemap/blob/master/examples/notebooks/02_using_basemaps.ipynb)) 

![](https://i.imgur.com/P5B2f7p.gif)

**Comment by kylebarron** [comment]
I think the difference here is rendering Google Maps _tiles_ and rendering with the Google Maps _API_. When you're choosing among basemaps, you're selecting among _tile endpoints_, where you select the images to display, but you're displaying them with Leaflet.

I think we'd prefer to have the option to render the `EarthEngineLayer` _with the Google Maps API_. That means that a user has the entire Google Maps API at their fingertips, because deck.gl is rendering into their API, so to speak.
