### ISSUE TITLE
Test with new pydeck releases with jupyter lab

### ISSUE THREAD

**Issue by kylebarron** [UnfoldedInc/earthengine-layers#78]
I tested with the new pydeck beta, 0.4.0b1, but I couldn't get any deck plots to show. The console complained:

```
Module @deck.gl/jupyter-widget, semver range 8.2.0-alpha.2 is not registered as a widget module
```
I've seen this before where there's a mismatch between the deck version pydeck expects and the JS version loaded. `deck.version` in the console prints `8.2.0-alpha.1`.

I'm not sure if this is somehow an error on my end, or if pydeck is accidentally still bundling `8.2.0-alpha.1`. 

cc @ajduberstein

**Comment by ajduberstein** [comment]
The JS bundled with pydeck is only for notebooks. JS installed in JupyterLab is downloaded via unpkg.

For these beta installations you need to manually upgrade your `@deck.gl/jupyter-widget` installations. `jupyter labextension install @deck.gl/jupyter-widget@8.2.0-alpha.2` should do the trick.

**Comment by kylebarron** [comment]
I was able to upgrade by running 

```
jupyter labextension uninstall @deck.gl/jupyter-widget
jupyter labextension install @deck.gl/jupyter-widget@8.2.0-alpha.2
```

but I'm still getting some errors. I think it might be good to create an issue in visgl/deck.gl to debug tomorrow.

**Comment by kylebarron** [comment]
Should be fixed by https://github.com/visgl/deck.gl/pull/4652

**Comment by kylebarron** [comment]
Works for me with JupyterLab 2
