### ISSUE TITLE
Layer control

### ISSUE THREAD

**Issue by giswqs** [UnfoldedInc/earthengine-layers#88]
Does pydeck have a layer control that can be used to toggle layers on/off, just like the ipyleaflet package.This would be very helpful when multiple Earth Engine layers are added to the map. I can't seem to find information about the layer control on the pydeck [documentation](https://deckgl.readthedocs.io/en/stable/). 

![](https://i.imgur.com/RtxP59K.png)

**Comment by ibgreen** [comment]
@giswqs The `EarthEngineLayer` is a deck.gl layer and as such inherits a `visible` prop, so if you set `visible: false` in the layer you can hide it programmatically from Python. 

That said, I assume you'd like this work without having to add UI logic to your notebook.

Will refer to @ajduberstein regarding having something like this built-in to pydeck.
